---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  INSTALL_DOCKER_REPO: 1

jobs:
  build-image-arm64:
    name: build-image.linux/arm64
    needs: build
    runs-on: ghcr.io/cirruslabs/ubuntu-runner-arm64:latest-sm
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: build-image
        uses: ./.github/actions/build-image
        with:
          architecture: linux/arm64
