---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  INSTALL_DOCKER_REPO: 1

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: build package
        run: ./tests/ci/setup.sh build
        env:
          SKIP_IMAGE_BUILD: true

      - name: set matrix for build
        id: set-matrix
        run: |
          json=$(python .github/commands/matrix)
          echo $json
          echo "matrix=$json" >> $GITHUB_OUTPUT

      - name: upload packages
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  build-image-arm64:
    name: build-image.linux/arm64
    needs: build
    runs-on: ghcr.io/cirruslabs/ubuntu-runner-arm64:latest-sm
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: build-image
        uses: ./.github/actions/build-image
        with:
          architecture: linux/arm64
